### ISSUE TITLE
Unable to delete the schedule automatically once it's done for "triggerPipelineGateOnSchedule"

### ISSUE THREAD

**Issue by xiaogangwen** [electric-cloud/EF-Utilities#5]
The step calls "ectool deleteSchedule "$[/myProject/projectName]" "$[/mySchedule]" where $[/myProject/projectName] is substituted with the plugin project name. "$[/myJob/projectName]" might be what we want.

**Comment by lrochette** [comment]
It's a leftover of a time where the schedule was created in the Plugin.
It now needs to be deleted in the pipeline project: /mySchedule/projectName should do it
